name: Delete Failed and Yesterday's Workflow Runs

on:
  workflow_dispatch: # Allows manual run from Actions tab

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete failed workflow runs (including today)
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          delete_run_by_conclusion_pattern: failure
          keep_minimum_runs: 0

      - name: Delete workflow runs older than 1 day
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
