name: Delete Yesterday's Workflow Runs

on:
  workflow_dispatch: # Allows manual run from Actions tab

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs older than 1 day
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1         # Keeps runs from today (<24h), deletes older ones
          keep_minimum_runs: 0   # Set to 0 to ensure runs aren't saved
